import * as stylex from "@stylexjs/stylex";

export const todoStyles = stylex.create({
  shell: {
    width: "min(100% - 32px, 580px)",
    margin: "0 auto",
    padding: { default: "72px 0", "@media (max-width: 520px)": "40px 0" },
  },
  header: {
    display: "grid",
    gridTemplateColumns: { default: "1fr auto", "@media (max-width: 520px)": "1fr" },
    alignItems: "end",
    gap: "4px 24px",
    marginBottom: 24,
  },
  eyebrow: {
    gridColumn: "1 / -1",
    margin: 0,
    color: "#617064",
    fontSize: "0.78rem",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    overflowWrap: "normal",
  },
  heading: {
    margin: 0,
    fontFamily: "inherit",
    fontSize: "clamp(2.5rem, 8vw, 4.5rem)",
    fontWeight: 700,
    letterSpacing: "-0.06em",
    lineHeight: 0.95,
    overflowWrap: "normal",
  },
  remaining: { paddingBottom: 4, color: "#617064" },
  list: {
    display: "grid",
    gap: 10,
    // Restore the native list block margins removed by the shared foundation.
    margin: "1em 0",
    padding: 0,
    listStyle: "none",
  },
  surface: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#ccd7ce",
    borderRadius: 16,
    backgroundColor: "#fff",
    boxShadow: "0 12px 32px rgb(26 48 34 / 8%)",
    // The foundation targets list items directly; preserve their native wrapping.
    overflowWrap: "normal",
  },
  label: {
    display: "flex",
    minHeight: 64,
    alignItems: "center",
    gap: 14,
    padding: "12px 18px",
    cursor: "pointer",
  },
  checkbox: {
    width: 20,
    height: 20,
    // Preserve the native checkbox's physical offsets and appearance.
    margin: "3px 3px 3px 4px",
    padding: 0,
    appearance: "auto",
    accentColor: "#2b6b45",
    outline: { default: null, ":focus-visible": "revert" },
    outlineOffset: { default: null, ":focus-visible": "revert" },
  },
  title: { overflowWrap: "normal" },
  completed: { color: "#78837a", textDecoration: "line-through" },
  state: { margin: "1em 0", padding: 24, overflowWrap: "normal" },
  error: {
    display: "flex",
    alignItems: { default: "center", "@media (max-width: 520px)": "stretch" },
    flexDirection: { default: "row", "@media (max-width: 520px)": "column" },
    justifyContent: "space-between",
    gap: 16,
    padding: 24,
    marginBottom: 12,
    borderColor: "#d39c8e",
    backgroundColor: "#fff8f5",
  },
  errorMessage: { margin: 0, overflowWrap: "normal" },
  retry: {
    minHeight: 42,
    padding: "0 16px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#405849",
    borderRadius: 999,
    color: "#17211b",
    backgroundColor: "#fff",
    font: "inherit",
    cursor: "pointer",
    touchAction: "auto",
    outline: { default: null, ":focus-visible": "revert" },
    outlineOffset: { default: null, ":focus-visible": "revert" },
  },
});
