import * as stylex from "@stylexjs/stylex";

export const workbenchStyles = stylex.create({
  shell: {
    display: "grid",
    minHeight: "100vh",
    gridTemplateColumns: {
      default: "minmax(260px, 340px) 1fr",
      "@media (max-width: 840px)": "1fr",
    },
    backgroundColor: "#17211b",
  },
  sidebar: {
    display: "flex",
    minWidth: 0,
    flexDirection: "column",
    gap: 28,
    padding: 32,
    color: "#edf2ec",
  },
  eyebrow: {
    margin: "0 0 6px",
    color: "#a7b9aa",
    fontSize: "0.72rem",
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    overflowWrap: "normal",
  },
  heading: {
    margin: 0,
    fontFamily: "inherit",
    fontWeight: 700,
    letterSpacing: "-0.04em",
    overflowWrap: "normal",
  },
  h1: { fontSize: "2em" },
  h2: { fontSize: "1.5em" },
  description: {
    display: "block",
    marginTop: 8,
    color: "#a7b9aa",
    lineHeight: 1.45,
  },
  navigation: { display: "grid", gap: 8 },
  scenario: {
    display: "grid",
    gap: 4,
    padding: 14,
    border: "1px solid #405849",
    borderRadius: 12,
    color: "inherit",
    textDecoration: "none",
    outline: { default: null, ":focus-visible": "revert" },
    outlineOffset: { default: null, ":focus-visible": "revert" },
  },
  currentScenario: {
    borderColor: "#b7e2c1",
    color: "#17211b",
    backgroundColor: "#b7e2c1",
  },
  scenarioDescription: { color: "inherit", lineHeight: 1.35, opacity: 0.72 },
  details: { marginTop: "auto", color: "#a7b9aa" },
  summary: {
    outline: { default: null, ":focus-visible": "revert" },
    outlineOffset: { default: null, ":focus-visible": "revert" },
  },
  claims: {
    display: "grid",
    gap: 10,
    margin: "1em 0",
    paddingLeft: 18,
    fontSize: "0.82rem",
    lineHeight: 1.4,
  },
  claim: { overflowWrap: "normal" },
  stage: {
    minWidth: 0,
    padding: 32,
    borderRadius: { default: "24px 0 0 24px", "@media (max-width: 840px)": "24px 24px 0 0" },
    backgroundColor: "#edf2ec",
  },
  stageHeader: { width: "min(100%, 760px)", margin: "0 auto 20px" },
  stageDescription: { color: "#617064" },
  frame: {
    width: "min(100%, 760px)",
    minHeight: 620,
    margin: "0 auto",
    overflow: "hidden",
    border: "1px solid #ccd7ce",
    borderRadius: 20,
    backgroundColor: "#edf2ec",
    boxShadow: "0 24px 80px rgb(14 28 19 / 18%)",
  },
  error: {
    width: "min(100% - 32px, 620px)",
    margin: "12vh auto 0",
    padding: 32,
    border: "1px solid #d39c8e",
    borderRadius: 20,
    backgroundColor: "#fff8f5",
  },
  errorDescription: { color: "#754e43" },
  recoveryLink: {
    display: "inline-block",
    marginTop: 24,
    color: "#17211b",
    textUnderlineOffset: "auto",
    outline: { default: null, ":focus-visible": "revert" },
    outlineOffset: { default: null, ":focus-visible": "revert" },
  },
});
